# Generated by Django 4.2.1 on 2023-06-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Cetegory ', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Popular products ', 'verbose_name_plural': 'Popular products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='content',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
